---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars_files:
    - vars/{{ env }}.yml
    - vars/tmp/{{ env }}_vpc_info.yml

  tasks:

    - name: delete {{ app }}_{{ env }}_sg_web
      local_action:  
        module: ec2_group
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_web"
        description: security group for webservers
        state: absent

    - name: delete {{ app }}_{{ env }}_sg_database
      local_action:  
        module: ec2_group    
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_db"
        description: security group for databases
        state: absent

    - name: delete {{ app }}_{{ env }}_sg_nat
      local_action:  
        module: ec2_group    
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_nat"
        description: security group for nat
        state: absent

    - name: create security group for jump box instance
      local_action:
        module: ec2_group
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_jumpbox"
        description: security group for jump box
        state: absent