---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars_files:
    - vars/{{ env }}.yml
    - vars/{{ env }}_vpc_info.yml

  tasks:

    - name: create empty security group for webservers 
      local_action:  
        module: ec2_group    
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_web"
        description: security group for webservers

    - name: create empty security group for databases 
      local_action:  
        module: ec2_group    
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_db"
        description: security group for databases

    - name: create empty security group for nat
      local_action:  
        module: ec2_group    
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_nat"
        description: security group for nat

    - name: create security group for jump box instance
      local_action:
        module: ec2_group
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "{{ app }}_{{ env }}_sg_jumpbox"
        description: security group for jump box
