---
- name: delete vpc
  local_action:
    module: ec2_vpc
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    resource_tags: '{"Name":"{{ app }}_{{ env }}_vpc"}'
    state: absent
    wait: yes
