---  
- name: web instance provisioning
  local_action:
    module: ec2
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    group: "{{ app }}_{{ env }}_sg_web"
    instance_tags:
      app: "{{ app }}"
      class: web
      environment: "{{ env }}"
    vpc_subnet_id: "{{ subnet_public }}"
    count: 1
  register: ec2

- name: associate new EIP for the instance
  local_action:
    module: ec2_eip
    region: "{{ region }}"
    instance_id: "{{ item.id }}"
  with_items: ec2.instances

- name: database instance provisioning
  local_action:
    module: ec2
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    group: "{{ app }}_{{ env }}_sg_db"
    instance_tags:
      app: "{{ app }}"
      class: db
      environment: "{{ env }}"
    vpc_subnet_id: "{{ subnet_private }}"
    count: 1
    assign_public_ip: no
