---  
- name: create key pair public
  local_action:
    module: ec2_key
    region: "{{ region }}"
    name: "{{ keypair }}"
  register: mykey

- name: write to file
  local_action: shell echo "{{ item.value.private_key }}" > ~/.ssh/"{{ keypair }}".pem && chmod 600 ~/.ssh/"{{ keypair }}".pem
  with_dict: mykey
  when: item.value.private_key is defined
