---  
- name: NAT instance provisioning
  local_action:
    module: ec2
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ nat_instance_type }}"
    image: "{{ nat_image }}"
    wait: yes
    group: "{{ app }}_{{ env }}_sg_nat"
    instance_tags:
      app: "{{ app }}"
      class: nat
      environment: "{{ env }}"
    vpc_subnet_id: "{{ subnet_public }}"
    source_dest_check: no
    wait: yes
    count: 1
  register: ec2

- name: associate new EIP for the instance
  tags: eip
  local_action:
    module: ec2_eip
    region: "{{ region }}"
    instance_id: "{{ item.id }}"
  with_items: ec2.instances
  when: item.id is defined
